---

# The Fragnet Travis CI build script.
#
# For Gradle build hints checkout the following: -
#   https://guides.gradle.org/executing-gradle-builds-on-travisci
#   https://docs.travis-ci.com/user/languages/java/

os: linux
language: java
jdk: openjdk8

services:
- docker

stages:
  # The 'build' stage
  # - Compiles the code and also used to run unit tests.
- name: test
  # The 'publish' stage
  # - Assembles docker images and pushes the resultant images to Docker Hub.
  #   We execute the 'publish' stage and always publish an image
  #   on master or when tagged. When tagged the tag value is used for the
  #   image tag, when not tagged the published image tag is 'latest'.
- name: publish
  if: tag IS present OR branch == master

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

matrix:
  include:

  # Test-stage jobs...

#  - stage: test
#    name: Unit Test
#    script: scripts/test.sh

  # Publish-stage jobs...

  - stage: publish
    name: Docker Build and Push
    script: scripts/publish.sh
