version: '3.1'
services:
  neo4j:
    image: informaticsmatters/neo4j:3.5
    environment:
      NEO4J_dbms_memory_pagecache_size: 12g
      NEO4J_dbms_memory_heap_initial__size: 6g
      NEO4J_dbms_memory_heap_max__size: 6g
      NEO4J_dbms_directories_data: '/data'
      NEO4J_EDITION: community
      NEO4J_AUTH: neo4j/hts
      EXTENSION_SCRIPT: /data-loader/load_neo4j.sh
    volumes:
    - "/home/timbo/dev/docker-neo4j-frag/hts/data-loader:/data-loader:Z"
    - "/home/timbo/dev/docker-neo4j-frag/hts/data:/data:Z"
    - "/home/timbo/dev/docker-neo4j-frag/hts/logs:/logs:Z"
    ports:
    - "7474:7474"
    - "7687:7687"

  fragnet-services:
    image: squonk/fragnet-services:latest
    environment:
      NEOJ4_PASSWORD: hts
      CdkUseLegacyAtomContainer: 1
    ports:
    - "80:8080"
    depends_on:
      - neo4j
