---

# Gets graph data from the S3 bucket named in the 's3_fragnet_bucket' variable.
#
# The origin of the data will be defined using a "combination" reference,
# essentially a sub-directory of the bucket's "combination" directory.
# The combination is expected to contain all the nodes, relationships and
# headers along with a "load-neo4j.sh" (and optional "index-neo4j.sh) script -
# i.e.

- name: Get combination
  shell: aws s3 sync s3://{{ origin }} {{ graph_loader_directory }}
  vars:
    origin: "{{ s3_fragnet_bucket }}/combination/{{ combination }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  changed_when: false
