---

# Tasks to stop and reset the graph node.
# This is simple, it stops the container
# and removes the expected directories.

- import_tasks: "{{ role_path }}/tasks/stop.yaml"

- name: Remove graph directories
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  loop:
  - "{{ graph_loader_directory }}"
  - "{{ graph_db_directory }}"
  - "{{ graph_log_directory }}"
