---

# Tasks to stop and reset the graph node.
# This is simple, it stops the container
# and removes the expected directories.

- name: Stop (remove) containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
  - graph
  - fragnet-search
  become: yes
  ignore_errors: yes

