---

- name: Login (user)
  command: oc login https://{{ oc_master_hostname }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Get existing project
  command: oc get projects
  register: projects_result
  changed_when: False

- name: Create the Fragnet Search Project
  command: >
    oc new-project {{ fs_project }} --display-name='{{ fs_project_display_name }}'
  when: >
    not projects_result.stdout
    | regex_search('^%s\s' % fs_project, multiline=True)

# The default service account needs 'anyuid'
# as the fragnet search container uses tomcat

- name: Login (admin)
  command: oc login https://{{ oc_master_hostname }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Fragnet Search Project
  command: oc project {{ fs_project }}
  changed_when: False

- name: Get SA
  command: oc get sa
  register: sa_result
  changed_when: False

- name: Create SA
  command: oc create sa {{ fs_sa }}
  when: not sa_result.stdout | regex_search('^%s\s' % fs_sa, multiline=True)

- name: Add anyuid to SA
  command: >
    oc adm policy add-scc-to-user anyuid -z {{ fs_sa }}
  when: not sa_result.stdout | regex_search('^%s\s' % fs_sa, multiline=True)
