---

# Create the project

- name: Login (user)
  command: oc login https://{{ oc_master_hostname }} -u {{ oc_user }} -p {{ oc_user_password }}
  changed_when: False

- name: Deploy Project
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - project.yml.j2

# Create the service account
#
# The Fragnet Search service account needs 'anyuid'
# as its container uses tomcat

- name: Login (admin)
  command: oc login https://{{ oc_master_hostname }} -u {{ oc_admin }} -p {{ oc_admin_password }}
  changed_when: False

- name: Move to Fragnet Search Project
  command: oc project {{ fs_project }}
  changed_when: False

- name: Deploy SA
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - service-account.yml.j2

- name: Add anyuid to SA
  command: oc adm policy add-scc-to-user anyuid -z {{ fs_sa }}

# Configure the Fragnet Search Keycloak Client

- name: Add Keycloak Fragnet Search Client
  local_action:
    module: keycloak_client
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ oc_keycloak_server_url }}"
    auth_realm: master
    auth_username: "{{ oc_keycloak_admin }}"
    auth_password: "{{ oc_keycloak_admin_password }}"
    realm: "{{ oc_keycloak_realm }}"
    client_id: "{{ fs_keycloak_client_id }}"
    protocol: openid-connect
    base_url: https://{{ fs_route }}.{{ oc_master_hostname }}
    public_client: yes
    service_accounts_enabled: yes
    direct_access_grants_enabled: yes
    standard_flow_enabled: yes

# Deploy the application

- name: Deploy application objects
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - configmap.yml.j2
  - deployment.yml.j2
  - service.yml.j2
  - route.yml.j2
