---

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Install prerequisite Python modules
  pip:
    name:
    - openshift==0.10.0
    - jmespath==0.9.4
    extra_args: --user

# Go...

- include_tasks: deploy.yaml
  when: fs_deploy|bool
- include_tasks: undeploy.yaml
  when: not fs_deploy|bool
