---

# Un-deploy (uninstall) Fragnet Search.
#
# USE with EXTREME caution.

- name: Login (user)
  command: oc login https://{{ okd_master_hostname }} -u {{ okd_user }} -p {{ okd_user_password }}
  changed_when: False

# To un-deploy Fragnet Search, the fastest way is to
# simply delete the project.

- name: Get Projects
  command: oc get projects
  register: projects_result
  changed_when: False

- name: Delete Fragnet Search Project
  command: oc delete project/{{ fs_project }}
  when: projects_result.stdout|regex_search('^%s\s.*Active$' % fs_project, multiline=True)

- name: Wait for Fragnet Search project deletion
  command: oc get projects
  register: pj_cmd
  retries: 20
  delay: 30
  until: not pj_cmd.stdout|regex_search('^%s\s' % fs_project, multiline=True)
  changed_when: False

# Clean-up the infrastructure

- name: Remove Keycloak Fragnet Search Client
  local_action:
    module: keycloak_client
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ keycloak_server_url }}"
    auth_realm: master
    auth_username: "{{ keycloak_admin }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ keycloak_realm }}"
    client_id: "{{ fs_keycloak_client_id }}"
    state: absent
