---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(levelname)-7s - %(name)s/%(funcName)s :  # %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

loggers:
  FragnetSearch:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
