---

# Deploy and start the Fragnet Graph database.
#
# This assumes the fragnet_server_id EC2 service instance
# exists in the fragnet_server_region region.

- hosts: localhost
  gather_facts: no

  tasks:

  # Could be destructive/time-consuming.
  # Is the user sure?

  - name: Deploy {{ graph_name }}?
    pause:
      prompt: |-
        Are you sure you want to deploy the {{ graph_name }} database?
        This will stop the graph container, replacing it with a new graph.
        Press return to continue if you do and have.
        Press Ctrl+c and then "a" if you've changed your mind

  # Let's go...

  - name: Run the Role 'pre-flight check' Tasks
    include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - name: Run the Role 'start instances' Tasks
    include_role:
      name: fragnet
      tasks_from: start-instances.yaml
  - name: Run the Role 'stop graph' Tasks
    include_role:
      name: fragnet
      tasks_from: stop-graph.yaml

- hosts: graph
  gather_facts: no

  roles:
  - fragnet
