---

# Deploy and start the Fragnet Graph database.
#
# This assumes the fragnet_server_id EC2 service instance
# exists in the fragnet_server_region region.

- hosts: localhost
  gather_facts: no

  tasks:

  - include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml

  # Could be destructive/time-consuming.
  # Is the user sure?

  - name: Deploy {{ graph_name }}?
    pause:
      prompt: |-
        Are you sure you want to deploy the {{ graph_name }} database?
        This will stop the graph container, replacing it with a new graph.
        Press return to continue if you are happy to deploy.
        Press Ctrl+c and then "a" if you've changed your mind

- hosts: graph
  gather_facts: no

  tasks:

  - include_role:
      name: fragnet
      tasks_from: start-instances.yaml
  - include_role:
      name: fragnet
      tasks_from: stop-graph.yaml
  - include_role:
      name: fragnet
