---

- hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - include_role:
      name: fragnet
      tasks_from: start-instances.yaml
