---

- hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - include_role:
      name: fragnet
      tasks_from: start-instances.yaml

- hosts: graph
  gather_facts: no

  tasks:
  - wait_for_connection:
  - setup:
  - include_role:
      name: fragnet
      tasks_from: start-graph.yaml
  - include_role:
      name: fragnet
      tasks_from: start-fragnet-search.yaml
