---

- hosts: graph
  gather_facts: no

  tasks:
  - name: Run the Role 'pre-flight check' Tasks
    include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - name: Run the Role 'stop instances' Tasks
    include_role:
      name: fragnet
      tasks_from: stop-instances.yaml
