---

- hosts: graph

  tasks:
  - include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - include_role:
      name: fragnet
      tasks_from: stop-fragnet-search.yaml
  - include_role:
      name: fragnet
      tasks_from: stop-graph.yaml
