---

# A simple playbook that runs some tasks
# to test the Fragnet service.

- hosts: graph
  gather_facts: no

  tasks:
  - name: Run the Role 'pre-flight check' Tasks
    include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml
  - name: Wait for Connection
    wait_for_connection:
  - name: Gathering facts
    setup:
  - name: Run the Role 'test-fragnet' Tasks
    include_role:
      name: fragnet
      tasks_from: test-fragnet.yaml
