---

# A simple playbook that runs some tasks
# to test the Fragnet service.

- hosts: graph
  gather_facts: no

  tasks:
  - include_role:
      name: fragnet
      tasks_from: pre-flight-check.yaml

  - wait_for_connection:
  - setup:
  - include_role:
      name: fragnet
      tasks_from: test-fragnet.yaml
