---

# Gets graph data from the S3 bucket named in the 's3_fragnet_bucket' variable.
#
# The origin of the data will be defined using a "combination" reference,
# essentially a sub-directory of the bucket's "combination" directory.
# The combination is expected to contain all the nodes, relationships and
# headers along with a "load-neo4j.sh" (and optional index-neo4j.sh) script -
# i.e. the *full set of import files*.

- name: Assert combination
  fail:
    msg: You must provide a 'graph_origin_id' value
  when:
  - not graph_origin_id is defined
  - graph_origin_id|length == 0

- name: Display origin
  debug:
    msg: "{{ s3_fragnet_bucket }}/combination/{{ graph_origin_id }}"

- name: Get combination
  shell: aws s3 sync s3://{{ origin }} {{ graph_loader_path }}
  vars:
    origin: "{{ s3_fragnet_bucket }}/combination/{{ graph_origin_id }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  changed_when: false
