---

# Pre-flight checks...

# Has the user defined suitable key variables?

- name: Assert keycloak variables
  fail:
    msg: "You must provide 'keycloak' variables"
  when: keycloak_server_url == ''

- name: Assert keycloak variables
  fail:
    msg: "You must provide a neo4j password"
  when: graph_password == ''

# Ready to go...

- include_tasks: set-database-facts.yaml

# Preparation script for the graph node.
# Here we check the binary tools, directories, files etc.
# that are needed for the graph database.

- name: Install tools
  package:
    name: "{{ item }}"
  become: yes
  loop:
  - docker-1.13.1

- name: Create graph directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
  become: yes
  loop:
  - "{{ graph_loader_path }}"
  - "{{ graph_db_path }}"
  - "{{ graph_log_path }}"
  - "{{ ansible_env.HOME }}/fragnet"

- name: Install pip
  easy_install:
    name: pip
    state: latest
  become: yes

- name: Install Python packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  become: yes
  loop:
  - { name: awscli, version: 1.16.91 }
  - { name: docker-py, version: 1.10.6 }

- name: Start Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  loop:
  - docker

- name: Add authorised users
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
  - public_keys/*
