---

# Has the user defined suitable key variables?

- name: Assert keycloak variables
  fail:
    msg: "You must provide a neo4j password"
  when: graph_password == ''

# Launches the Graph DB (neo4j in this case)
# using the loader directory as an input.
# The graph DB is built locally on the cluster
# by the build task in the 'prepare.yaml' play.
#
# The 'import_dir' is the one referred to in the import script

- name: Start graph container
  docker_container:
    name: graph
    image: informaticsmatters/docker-neo4j:{{ graph_version }}
    published_ports:
    - 7474:7474
    - 7687:7687
    env:
      NEO4J_AUTH: neo4j/{{ graph_password }}
      NEO4J_dbms_memory_pagecache_size: 20G
      NEO4J_dbms_memory_heap_initial__size: 8G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_directories_data: /neo4j/graph
      NEO4J_dbms_directories_logs: /neo4j/log
      NEO4J_dbms_connector_bolt_advertised__address: "{{ inventory_hostname }}:7687"
      NEO4J_EDITION: community
      IMPORT_DIRECTORY: /data-loader
      IMPORT_TO: graph
      EXTENSION_SCRIPT: /data-loader/{{ graph_loader_script }}
    volumes:
    - "{{ graph_loader_path }}:/data-loader:Z"
    - "{{ graph_db_path }}:/neo4j/graph:Z"
    - "{{ graph_log_path }}:/neo4j/log:Z"
  become: yes

# Optionally wait for the graph database.
# The graph DB can take a lot of time to initialise
# so this step can be avoided by clearing 'wait_for_graph'.
#
# If you don't wait you will still need to wait to use the DB
# until neo has finished initialising.

- name: Wait for graph
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 7474
    delay: 30
    sleep: 20
    timeout: "{{ minutes_to_wait_for_graph|int * 60 }}"
  when: wait_for_graph
