---
name: build and push latest

on:
- push

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Assembe the code
      run: ./gradlew assemble

  build-and-publish-latest:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
    - name: Build
      run: ./gradlew buildDockerImage -x test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Push latest
      run: docker push squonk/fragnet-services:latest
