---
name: build and push stable

# Actions for an 'official' tag.
#
# An official tag is a 2 or 3-digit value (i.e. 'N.N[.N]').
# We publish images using the tag as a tag and one using 'stable' as s tag.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)
#
# For automated deployment we expect the following in the environment: -
#
# (none)

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+'

jobs:
  push-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./gradlew buildDockerImages -x test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    # It's an official tag so push
    # the tagged images and a 'stable' form
    - name: Push stable
      run: |
        docker tag squonk/cdk-depict:latest squonk/cdk-depict:stable
        docker tag squonk/cdk-depict:latest squonk/cdk-depict:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/cdk-depict:stable
        docker push squonk/cdk-depict:${{ env.GITHUB_REF_SLUG }}
        docker tag squonk/fragnet-depict:latest squonk/fragnet-depict:stable
        docker tag squonk/fragnet-depict:latest squonk/fragnet-depict:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/fragnet-depict:stable
        docker push squonk/fragnet-depict:${{ env.GITHUB_REF_SLUG }}
        docker tag squonk/fragnet-search:latest squonk/fragnet-search:stable
        docker tag squonk/fragnet-search:latest squonk/fragnet-search:${{ env.GITHUB_REF_SLUG }}
        docker push squonk/fragnet-search:stable
        docker push squonk/fragnet-search:${{ env.GITHUB_REF_SLUG }}

  # Deploy 'Depict'
  # (to the AWX/im-main Environment)
  trigger-awx-depict:
    needs: push-stable
    runs-on: ubuntu-latest
    environment: awx/im-main
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: informaticsmatters/trigger-awx-action@v1
      with:
        template: FragnetDepict
        template-host: ${{ secrets.AWX_HOST }}
        template-user: ${{ secrets.AWX_USER }}
        template-user-password: ${{ secrets.AWX_USER_PASSWORD }}
        template-var: fs_image_tag
        template-var-value: ${{ env.GITHUB_REF_SLUG }}

  # Deploy 'Search API'
  # (to the AWX/DLS Development Environment)
  trigger-awx-search:
    needs: push-stable
    runs-on: ubuntu-latest
    environment: awx/dls-dev
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: informaticsmatters/trigger-awx-action@v1
      with:
        template: FragnetSearch API
        template-host: ${{ secrets.AWX_HOST }}
        template-user: ${{ secrets.AWX_USER }}
        template-user-password: ${{ secrets.AWX_USER_PASSWORD }}
        template-var: fs_image_tag
        template-var-value: ${{ env.GITHUB_REF_SLUG }}
