---
name: build and push latest

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)
#
# For automated deployment we expect the following in the environment: -
#
# (none)


on:
  push:
    branches:
    - 'master'

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: ./gradlew buildDockerImages -x test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Push latest
      run: |
        docker push squonk/fragnet-depict:latest
        docker push squonk/fragnet-search:latest
